version: '3.1'

services:
  db:
    build: .
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project_database
    ports:
      - "3306:3306"
    volumes:
      - ./Data:/docker-entrypoint-initdb.d
